print("a", "b", "c")
print("a", "b", "c", sep="*")
minus = "-"
print("a", "b", "c", sep=minus)
print("a", "b", "c", end="\n")
print("a", "b", "c", sep="*", end="-")
print()
print("a", "\n", "b", "\n", "c", sep="*", end="#")
print()
print("a", "b", "c", sep="", end="")
print()
print("Python", end="\n\n\n")
print("YES", sep="!", end="#")
print("NO", sep="#", end="!")
print()

print("a", "b", "c", sep="*")
print("d", "e", "f", sep="**", end="")
print()
print()
print("БЕСКОНЕЧНОСТЬ", "НЕ", "ПРЕДЕЛ", "!", sep="_")
print()
print("БЕСКОНЕЧНОСТЬ_НЕ_ПРЕДЕЛ!")
print()
print("БЕСКОНЕЧНОСТЬ", "НЕ", "ПРЕДЕЛ!", sep="_", end="!")
print()
print("БЕСКОНЕЧНОСТЬ", "НЕ", "ПРЕДЕЛ", sep="_", end="")
print("!")
print()
print()
print("БЕСКОНЕЧНОСТЬ_НЕ_ПРЕДЕЛ", end="")
print("!")
